In [8]:
import numpy as np

li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 2 11  9 15 19]
[12 11 11  4 16]


In [10]:
li = [i+1 for i in li]
li

[3, 4, 5, 6, 7]

In [17]:
a = a + 1
a

array([ 7, 16, 14, 20, 24])

In [19]:
c = a + b
c

array([19, 27, 25, 24, 40])

In [20]:
d = a - b
d


array([-5,  5,  3, 16,  8])

In [22]:
e = a * b
e

array([ 84, 176, 154,  80, 384])

In [23]:
f = a / b
f

array([ 0.58333333,  1.45454545,  1.27272727,  5.        ,  1.5       ])

In [24]:
g = a // b
g

array([0, 1, 1, 5, 1])

In [25]:
h = a ** b
h

array([         13841287201,       17592186044416,        4049565169664,
                     160000, -2936065482068852736])

In [32]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin()) #index for min element
print(a.max())
print(a.argmax())

[ 7 16 14 20 24]
81
16.2
7
0
24
4


## Relational Operations

In [34]:
print(a)
print(b)

[ 7 16 14 20 24]
[12 11 11  4 16]


In [36]:
a > b

array([False,  True,  True,  True,  True], dtype=bool)

In [37]:
a < b

array([ True, False, False, False, False], dtype=bool)

In [38]:
a == b

array([False, False, False, False, False], dtype=bool)

## Logical Operations

In [40]:
print(np.logical_or(a, b))
print(np.logical_and(a, b))


[ True  True  True  True  True]
[ True  True  True  True  True]


In [42]:
a[2] = 0
print(a)
print(np.logical_not(a))

[ 7 16  0 20 24]
[False False  True False False]


# Boolean Indexing

In [1]:
import numpy as np

a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[18  4 18 12 15  3 16 17]


In [2]:
print(b > 10)

[ True False  True  True  True False  True  True]


In [3]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[ True False  True  True  True False  True  True]
[18 18 12 15 16 17]


In [4]:
new_arr = b[b > 10]
new_arr

array([18, 18, 12, 15, 16, 17])

In [5]:
new_arr = b[(b > 10) & (b < 18)]
new_arr

array([12, 15, 16, 17])

In [6]:
print(b)
c = b
c

[18  4 18 12 15  3 16 17]


array([18,  4, 18, 12, 15,  3, 16, 17])

In [7]:
c[:3] = 19
print(c)
c[c > 15] = 100
c

[19 19 19 12 15  3 16 17]


array([100, 100, 100,  12,  15,   3, 100, 100])

In [8]:
print(b)



[100 100 100  12  15   3 100 100]


In [9]:
print(b[b == 100])

[100 100 100 100 100]


In [10]:
ind = np.where(b == 100)
ind

(array([0, 1, 2, 6, 7], dtype=int32),)

In [11]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100  12  15   3 100 100]


In [12]:
ind = np.where(b == 100)
print(ind)
print(a[ind]) #print only those indexes of a where b==10

(array([0, 1, 2, 6, 7], dtype=int32),)
['t' 'b' 'r' 'z' 'a']


### Boolean Indexing -2D

In [1]:
import numpy as np
a = np.random.randint(1, 30, (5, 6))
print(a)

[[22  8 17 18 19 24]
 [19 28  5  2 23 23]
 [13 20 29 19 19 28]
 [26 18 24 27  2  3]
 [11 24 13  1 18  5]]


In [3]:
bool_arr = a > 20
print(bool_arr)

[[ True False False False False  True]
 [False  True False False  True  True]
 [False False  True False False  True]
 [ True False  True  True False False]
 [False  True False False False False]]


In [6]:
x=a[bool_arr]

In [7]:
ans = a[bool_arr]
print(ans)

[22 24 28 23 23 29 28 26 24 27 24]


In [8]:
if type(x) == type(ans):
    print("y")

y


In [9]:
b = a
print(a)

[[22  8 17 18 19 24]
 [19 28  5  2 23 23]
 [13 20 29 19 19 28]
 [26 18 24 27  2  3]
 [11 24 13  1 18  5]]


In [10]:
b[bool_arr] = 100
print(b)

[[100   8  17  18  19 100]
 [ 19 100   5   2 100 100]
 [ 13  20 100  19  19 100]
 [100  18 100 100   2   3]
 [ 11 100  13   1  18   5]]


In [11]:
c = np.random.randint(1, 10, (2, 2))
print(c)

[[2 4]
 [4 5]]


In [12]:
c_bool = np.array([[True, False], [False, True], [True, True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [13]:
print(c[c_bool]) #different dimenet of c and c_bool so error

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [15]:
print(b)

[[100   8  17  18  19 100]
 [ 19 100   5   2 100 100]
 [ 13  20 100  19  19 100]
 [100  18 100 100   2   3]
 [ 11 100  13   1  18   5]]


In [16]:
bool_arr = b[:, 3] == 100
print(bool_arr)

[False False False  True False]


In [17]:
b[bool_arr, 3] = 99
print(b)

[[100   8  17  18  19 100]
 [ 19 100   5   2 100 100]
 [ 13  20 100  19  19 100]
 [100  18 100  99   2   3]
 [ 11 100  13   1  18   5]]


# Exercise


Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements.
Output Format :
index1 index2 index3 ..

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
a=np.array([1,2,0,0,4,0])
b=np.where(a!=0)
for i in b:
    print(*i,end=" ")

Given an integer array of size 10. Print the index of elements which are multiple of 3.
Note: Generate the following array
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
Print the index of elements.
Output Format :
index1 index2 index3 ... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
a=np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
b=np.where(a%3==0)
for i in b:
    print(*i,end=' ')

Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.
Output Format :
firstElement secondElement  ... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[a%2==1]=-1
b=a
for i in a:
    print(i,end=' ')
   #using *i shows error in this : when we use the where function the output is returned in the form of a tuple so we cant use *i in this

Given an integer array of size 10 and replace the first occurrence of maximum value by 0?
Note: Generate the following array
array([11, 2, 13, 4, 15, 6, 27, 8, 19])
Print the Numpy array.
Output Format :
firstElement
secondElement 
... 

In [ ]:
import numpy as np
a=np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
a[a.argmax()]=0
for i in a:
    print(i)

Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.

In [1]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
a=np.arange(1,11)
b=[(a>=3) & (a<=8)]
a[b]*=-1
for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


<ipython-input-1-5073df41bce7>:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  a[b]*=-1


Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
Print the Numpy array.

In [ ]:
## Where returns a nd array
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
ind=np.where(height>155)
for i in ind:
    for j in i:
        print(age[j], end=' ')
        print(height[j])


Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
a=np.array([[21 ,20 ,19, 18 ,17],
          [16, 15, 14, 13, 12],
          [11, 10 , 9 , 8 , 7],
          [ 6 , 5 , 4 , 3 , 2]]) 

# b=a[np.argsort(a[:, 1])]
b=a[a[:,1].argsort()]

print(b)

