In [2]:
import tensorflow as tf

In [4]:
 a= tf.constant(2)
 b=tf.constant(9)

In [6]:
print(a)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [14]:
c=a+b
#not performing addition

In [17]:
print(c)

tf.Tensor(11, shape=(), dtype=int32)


In [20]:
a1=tf.constant([[3,3]])
a1

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[3, 3]], dtype=int32)>

In [21]:
a2=tf.constant([[3],[3]])
a2

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[3],
       [3]], dtype=int32)>

In [22]:
tf.matmul(a1,a2)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[18]], dtype=int32)>

You can't change the value of a constant.


In [24]:
a = tf.constant(1)
a = tf.constant(2)
a
#Here we aren’t changing the constant, we have created another constant with different value. Python variable a is not a constant.

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [28]:
 a= tf.constant(2)
 b=tf.constant(9)
 c=tf.add(a,b)
 c

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [5]:
x=tf.Variable(100)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>

In [7]:
y=tf.Variable(3)
y

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [9]:
sum=tf.add(x,y)
sum

<tf.Tensor: shape=(), dtype=int32, numpy=103>

In [12]:
y.assign(45)
y

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=45>

In [15]:
sum=tf.add(x,y)
sum

<tf.Tensor: shape=(), dtype=int32, numpy=145>

In [16]:
y.assign(4.5)
y 

TypeError: ignored