In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
X = np.array([[ 1., -1.,  2.],
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])

In [3]:
X_scaled = preprocessing.scale(X)
#centers it around mean i.e makes mean 0 and variance 1
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [4]:
X_scaled.mean(axis = 0)

array([0., 0., 0.])

In [5]:
X_scaled.std(axis= 0) 

array([1., 1., 1.])

In [6]:
#when data divided in training n testing n we want to scale both using same parameters for both
scaler = preprocessing.StandardScaler() #similarly minmaxscaler,absolutescaler
scaler.fit(X)
#x:training data

scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [8]:
X_test = [[1,1,0]]
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])

In [ ]:
Which of the following does sklearn.preprocessing do by default?
scale data to unit variance
center data before scaling